final Map<String, String> teacherLookupTable = {
    "Gsh": "Herr Dr Glashagen",
    "Gnz": "Herr Gonzales",
    "Boo": "Frau Boose",
    "FPl": "Frau Plath",
    "Bdt": "Herr Brandt",
    "Bhr": "Frau Becher",
    "Esm": "Frau Eismann",
    "FMö": "Frau Möritz",
    "Mnk": "Frau Mohnke",
    "Hnk": "Frau Heinkel",
    "Möl": "Herr Möller",
    "Lhm": "Herr Lehmann",
    "Swz": "Frau Schwarz",
    "Rth": "Frau Roth",
    "Bck": "Herr Brauckmann",
    "Wit": "Frau Wittner",
    "Sch": "Keine Ahnung",
    "Lmz": "Frau Lemanzcik",
    "Dpp": "Frau Deppermann",
    "Hnz": "Frau Henze",
    "HPl": "Herr Plath",
    "HMö": "Herr Dr Möller",
    "Gri": "Frau Griebel",
    "Slz": "Frau Scholz",
    "Gmn": "Herr Giermann",
    "Stw": "Herr Steinwehr",
    "SZi": "Frau Scholze Zimmermann",
    "Lck": "Herr Lücke",
    "Lgn": "Frau Lingnau",
    "Zer": "Herr Zehrt",
    "Tsk": "Frau Tschierschky",
    "Kdr": "Frau Kodera",
    "Bor": "Frau Borchert",
    "Grk": "Frau Gurk",
    "Egl": "Frau Engel",
    "Krt": "Frau Kritzel",
    "Rßm": "Herr Roßmann",
    "Grw": "Herr Gerwien",
    "Krg": "Herr Krüger",
    "Fnb": "Frau Finsterbusch",
    "Pnk": "Frau Pahnke",
    "Kap": "Herr Dr Kappler",
    "Lbs": "Frau Liebisch",
    "Bnk": "Frau (Anna) Benischke",
    "Gie": "Frau Giersch",
    "Bau": "Herr Bauer",
    "Lcs": "Frau Lucius",
    "Gis": "Herr Giese",
    "Ttz": "Frau Tietze",
    "SCo": "Frau Scharwe",
    "Mlf": "Frau Millfahrt",
    "Jhn": "Frau Jahn",
    "Stf": "Herr Steinfeld",
    "Vol": "Herr Voll",
    "Krs": "Herr Krause",
    "MBnk": "Frau (Marie) Benischke",
    "Slr": "Frau Scheller",
    "Nee": "Herr Neels",
    "Sdt": "Herr Schmidt",
};